# Generated by Django 4.2.7 on 2023-12-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
